name: yeast_scrna
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=4.4.2
  - r-seurat
  - samtools
  - bioconda::subread
  - bioconda::hisat2
  - bioconductor-geoquery
  - bioconductor-deseq2
  - r-biocmanager
  - r-tidyverse
  - r-matrix
  - r-mass
  - r-patchwork
  - r-data.table
  - r-ggplot2
  - r-dplyr
  # common system libs
  - curl
  - openssl
  - libxml2
  - zlib
